name: Create Release

on:
  push:
    branches:
      - main
jobs:
  releaseInfo:
    name: Dump info
    runs-on: ubuntu-latest
    outputs:
      runRelease: ${{ steps.PR.outputs.pr && contains(fromJSON(steps.PR.outputs.pr).labels.*.name, 'release') }}
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: |
          echo ${{ needs.releaseInfo.outputs.runRelease }}
      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prJSON}"
        if: steps.PR.outputs.pr_found == 'true'
        env:
          # JSON object with the full PR object
          # toJSON(fromJSON(...pr)) parses it into memory and then format is with pretty-print.
          prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          # Direct access to common PR properties
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
          prLabel: ${{ steps.PR.outputs.pr_labels }}
  createRelease:
    needs: releaseInfo
    if: needs.releaseInfo.outputs.runRelease
    runs-on: ubuntu-latest
    steps:
         - run: |
            echo ${{ needs.releaseInfo.outputs.runRelease }}
