name: Create Release

on:
  push:
    branches:
      - main
jobs:
  createRelease:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
         - run: |
            echo ${{ needs.releaseInfo.outputs.runRelease }}
