name: Create Release

on:
  push:
    branches:
      - main
jobs:
  releaseInfo:
    name: Dump info
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: |
          echo ${{ needs.releaseInfo.outputs.runRelease }}
      - run: echo "PR Label is: ${prLabel}"
        if: steps.PR.outputs.pr_found == 'true'
        run: |
            echo ${{ prLabel }}
        env:
          prLabel: ${{ steps.PR.outputs.pr_labels }}

